---
- hosts: 172.31.17.62
  become: yes
  tasks:
  - include: myfile.yml
  - name: install webserver
    apt:
     name: apache2
  - name: copy index file into node side
    copy:
     src: myindexpage
     dest:  /var/www/html/index.html
    notify: restartwebserver  

  - name: copy dyno files into nodes
    template:
      src: mydynoindex.j2
      dest:  /var/www/html/index.
    notify: restartwebserver

  - name: download internet files
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz

  handlers:
  - name: restartwebserver
    service:
       name: apache2
       state: restarted