---
- hosts: 172.31.17.62
  become: yes
  tasks:
  - include: myfile.yml
  - name: install webserver
    apt:
     name: apache2
  - name: copy index file into node side
    copy:
     src: myindexpage
     dest:  /var/www/html/index.html   