---
- hosts: 172.31.17.62
  become: yes
  tasks:
  - name: i want to create mytest file
    file:
      path:  /home/ubuntu/mytestfile
      state: touch

  - name: i want to install webserver
    apt:
      name: apache2
      state: present