---
# tasks file for mytomcatrole
- include_tasks: myuser.yml
- include_tasks: installjava.yml
- include_tasks: downloadtomcat.yml
- include_tasks: permissions.yml
- include_tasks: tomcatDashboard.yml
- include_tasks: tomservice.yml
- include_tasks: tomstart.yml



